version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container-source
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_USER: victor
      MYSQL_PASSWORD: senha123
      MYSQL_DATABASE: movies
    ports:
      - "3306:3306"
