version: '3.8'

services:
  mysql:
    image: mysql:9.0
    container_name: mysql-container-target
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_USER: victor
      MYSQL_PASSWORD: senha123
      MYSQL_DATABASE: movies
    ports:
      - "3307:3306"
