version: '3.8'

services:
  mysql1:
    image: mysql:latest
    container_name: mysql_source
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_USER: victor
      MYSQL_PASSWORD: senha123
      MYSQL_DATABASE: movies
    ports:
      - "3306:3306"
  mysql2:
    image: mysql:latest
    container_name: mysql_target
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_USER: victor
      MYSQL_PASSWORD: senha123
      MYSQL_DATABASE: movies
    ports:
      - "3307:3306" 
